global_configs= "-payload_sz=8 -threads=24 -worker_num=6 -port=8000 -server_gid=fe80:0000:0000:0000:248a:0703:009c:7c94"

[[pass]]
host = "val01"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./connect_lite_worker -addr=val01 -run_sec=25'

[[pass]]
host = "val02"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./connect_lite_worker -addr=val02 -run_sec=25'

[[pass]]
host = "val03"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./connect_lite_worker -addr=val03 -run_sec=25'

[[pass]]
host = "val04"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./connect_lite_worker -addr=val04 -run_sec=25'

[[pass]]
host = "val05"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./connect_lite_worker -addr=val05 -run_sec=25'

[[pass]]
host = "val06"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./connect_lite_worker -addr=val06 -run_sec=25'



[[pass]]
host = "val09"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./connect_lite_trigger -worker_addrs="val01 val02 val03 val04 val05 val06" -run_sec=20'



