global_configs= "-or_sz=2 -payload_sz=96 -write_imm=0 -undefok=write_imm,or_sz,threads -port=8000"

# Analyser
[[pass]]
host = "val10"
path = ''
#cmd  = 'cd projects/krdmakit/exp; ./racing_hash_analyser -host_len=10 -threads=1 -run_sec=50 -tick_interval_us=1000'
cmd  = 'cd projects/krdmakit/exp; ./racing_hash_analyser -host_len=10 -threads=1 -run_sec=50 -tick_interval_us=1000000'

# wokers
[[pass]]
host = "val01"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./racing_hash_kernel_elastic_worker -host=0 -use_rc=1 -analyser_addr=val10:8000 -tick_interval_us=100 -threads=24 -run_sec=40 -server_gid=fe80:0000:0000:0000:248a:0703:009c:7c94'

[[pass]]
host = "val02"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./racing_hash_kernel_elastic_worker -host=1 -use_rc=1 -analyser_addr=val10:8000 -tick_interval_us=100 -threads=24 -run_sec=40 -server_gid=fe80:0000:0000:0000:248a:0703:009c:7c94'

[[pass]]
host = "val03"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./racing_hash_kernel_elastic_worker -host=2 -use_rc=1 -analyser_addr=val10:8000 -tick_interval_us=100 -threads=24 -run_sec=40 -server_gid=fe80:0000:0000:0000:248a:0703:009c:7c94'


[[pass]]
host = "val04"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./racing_hash_kernel_elastic_worker -host=3 -use_rc=1 -analyser_addr=val10:8000 -tick_interval_us=100 -threads=24 -run_sec=40 -server_gid=fe80:0000:0000:0000:248a:0703:009c:7c94'

[[pass]]
host = "val05"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./racing_hash_kernel_elastic_worker -host=4 -use_rc=1 -analyser_addr=val10:8000 -tick_interval_us=100 -threads=24 -run_sec=40 -server_gid=fe80:0000:0000:0000:248a:0703:009c:7c94'

[[pass]]
host = "val06"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./racing_hash_kernel_elastic_worker -host=5 -use_rc=1 -analyser_addr=val10:8000 -tick_interval_us=100 -threads=24 -run_sec=40 -server_gid=fe80:0000:0000:0000:248a:0703:009c:7c94'

[[pass]]
host = "val07"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./racing_hash_kernel_elastic_worker -host=6 -use_rc=1 -analyser_addr=val10:8000 -tick_interval_us=100 -threads=24 -run_sec=40 -server_gid=fe80:0000:0000:0000:248a:0703:009c:7c94'

[[pass]]
host = "val08"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./racing_hash_kernel_elastic_worker -host=7 -use_rc=1 -analyser_addr=val10:8000 -tick_interval_us=100 -threads=24 -run_sec=40 -server_gid=fe80:0000:0000:0000:248a:0703:009c:7c94'

[[pass]]
host = "val09"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./racing_hash_kernel_elastic_worker -host=8 -use_rc=1 -analyser_addr=val10:8000 -tick_interval_us=100 -threads=24 -run_sec=40 -server_gid=fe80:0000:0000:0000:248a:0703:009c:7c94'


[[pass]]
host = "val10"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./racing_hash_trigger -worker_addrs="val01 val02 val03 val04 val05 val06 val07 val08 val09" -threads=1'




