global_configs = "-threads=24 -port=8000 -worker_num=1"


[[pass]]
host = "val08"
path = ''
cmd = 'cd projects/krdmakit/exp; ./connect_user_server -run_sec=20'



[[pass]]
host = "val01"
path = ''
cmd = 'cd projects/krdmakit/exp; ./connect_user_worker -addr=val01 -kv_addr=val08:8000 -run_sec=15'

[[pass]]
host = "val02"
path = ''
cmd = 'cd projects/krdmakit/exp; ./connect_user_worker -addr=val02 -kv_addr=val08:8000 -run_sec=15'

[[pass]]
host = "val03"
path = ''
cmd = 'cd projects/krdmakit/exp; ./connect_user_worker -addr=val03 -kv_addr=val08:8000 -run_sec=15'

[[pass]]
host = "val04"
path = ''
cmd = 'cd projects/krdmakit/exp; ./connect_user_worker -addr=val04 -kv_addr=val08:8000 -run_sec=15'

[[pass]]
host = "val05"
path = ''
cmd = 'cd projects/krdmakit/exp; ./connect_user_worker -addr=val05 -kv_addr=val08:8000 -run_sec=15'



[[pass]]
host = "val14"
path = ''
cmd = 'cd projects/krdmakit/exp; ./connect_user_trigger -worker_addrs="val01 val02 val03 val04 val05" -run_sec=5'






