global_configs= "-payload_sz=8 -threads=24 -worker_num=5 -port=8000 -server_gid=fe80:0000:0000:0000:ec0d:9a03:00ca:31d8"

[[pass]]
host = "val01"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./connect_krc_worker -addr=val01 -run_sec=25'

[[pass]]
host = "val02"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./connect_krc_worker -addr=val02 -run_sec=25'

[[pass]]
host = "val08"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./connect_krc_worker -addr=val08 -run_sec=25'

[[pass]]
host = "val04"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./connect_krc_worker -addr=val04 -run_sec=25'

[[pass]]
host = "val05"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./connect_krc_worker -addr=val05 -run_sec=25'


[[pass]]
host = "val09"
path = ''
cmd  = 'cd projects/krdmakit/exp; ./connect_krc_trigger -worker_addrs="val01 val02 val08 val04 val05" -run_sec=20'



